<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Biblioteca.Presentacion</RootNamespace>
    <StartupObject>Biblioteca.Presentacion.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Biblioteca.Dominio\Biblioteca.Dominio.csproj" />
    <ProjectReference Include="..\Biblioteca.Negocio\Biblioteca.Negocio.csproj" />
  </ItemGroup>

</Project>
